.PHONY: clean All

All:
	@echo "----------Building project:[ ArCondicionado - Debug ]----------"
	@cd "ArCondicionado" && "$(MAKE)" -f  "ArCondicionado.mk"
clean:
	@echo "----------Cleaning project:[ ArCondicionado - Debug ]----------"
	@cd "ArCondicionado" && "$(MAKE)" -f  "ArCondicionado.mk" clean
